// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sofware_CMJC_Version_1._0.Contexto_CMJC;

#nullable disable

namespace CMJC.Migrations
{
    [DbContext(typeof(CMJC_Context))]
    partial class CMJCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Consulta", b =>
                {
                    b.Property<int>("ID_Consulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Consulta"));

                    b.Property<int>("CRecetas")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionExamenFisico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamenesAuxiliares")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FC")
                        .HasColumnType("int");

                    b.Property<string>("FR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("HistoriaConsultaDiagnosticosWord")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ID_HistoriaClinica")
                        .HasColumnType("int");

                    b.Property<double>("IMC")
                        .HasColumnType("float");

                    b.Property<string>("Interconsulta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAtencion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("PresionArterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SintomasySignos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Talla")
                        .HasColumnType("float");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.Property<string>("TipoAtencion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Consulta");

                    b.HasIndex("ID_HistoriaClinica");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Diagnostico", b =>
                {
                    b.Property<int>("ID_Diagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Diagnostico"));

                    b.Property<string>("CIE10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionDiagnostico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Consulta")
                        .HasColumnType("int");

                    b.Property<string>("TipoDiagnostico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Diagnostico");

                    b.HasIndex("ID_Consulta");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.HistoriaClinica", b =>
                {
                    b.Property<int>("ID_HistoriaClinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_HistoriaClinica"));

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AntecedentesFamiliares")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AntecedentesPatologicos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AntecedentesQuirurgicos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Paciente")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("ID_HistoriaClinica");

                    b.HasIndex("ID_Paciente")
                        .IsUnique();

                    b.HasIndex("ID_Usuario");

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.HistoriaUsuario", b =>
                {
                    b.Property<int>("ID_HistoriaUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_HistoriaUsuario"));

                    b.Property<int>("ID_HistoriaClinica")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("ID_HistoriaUsuario");

                    b.HasIndex("ID_HistoriaClinica");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("HistoriasUsuarios");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Paciente", b =>
                {
                    b.Property<int>("ID_Paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Paciente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aseguradora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AsignacionHistoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Consultas")
                        .HasColumnType("int");

                    b.Property<string>("DIdentidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("Date");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Paciente");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Receta", b =>
                {
                    b.Property<int>("ID_Receta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Receta"));

                    b.Property<byte[]>("ArchivoWord")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Consulta")
                        .HasColumnType("int");

                    b.Property<string>("NAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMIME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Receta");

                    b.HasIndex("ID_Consulta");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NHistoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Consulta", b =>
                {
                    b.HasOne("Sofware_CMJC_Version_1._0.Modelo.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Consultas")
                        .HasForeignKey("ID_HistoriaClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Diagnostico", b =>
                {
                    b.HasOne("Sofware_CMJC_Version_1._0.Modelo.Consulta", "Consulta")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("ID_Consulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.HistoriaClinica", b =>
                {
                    b.HasOne("Sofware_CMJC_Version_1._0.Modelo.Paciente", "Paciente")
                        .WithOne("HistoriaClinica")
                        .HasForeignKey("Sofware_CMJC_Version_1._0.Modelo.HistoriaClinica", "ID_Paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sofware_CMJC_Version_1._0.Modelo.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.HistoriaUsuario", b =>
                {
                    b.HasOne("Sofware_CMJC_Version_1._0.Modelo.HistoriaClinica", "HistoriaClinica")
                        .WithMany("HistoriasUsuarios")
                        .HasForeignKey("ID_HistoriaClinica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sofware_CMJC_Version_1._0.Modelo.Usuario", "Usuario")
                        .WithMany("HistoriasUsuarios")
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Receta", b =>
                {
                    b.HasOne("Sofware_CMJC_Version_1._0.Modelo.Consulta", "Consulta")
                        .WithMany("Recetas")
                        .HasForeignKey("ID_Consulta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Consulta", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.HistoriaClinica", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("HistoriasUsuarios");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Paciente", b =>
                {
                    b.Navigation("HistoriaClinica");
                });

            modelBuilder.Entity("Sofware_CMJC_Version_1._0.Modelo.Usuario", b =>
                {
                    b.Navigation("HistoriasUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
